services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: migration
      POSTGRES_PASSWORD: "4nlNhmFW0zzM7rksQe7x3b5I-sKqc9LX"
    volumes:
      - migration_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "MGoqym6Q2G0bZF49Qlx0mqMMdAIeUCEZ"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: migration_test
      POSTGRES_PASSWORD: "BPMTjZQPuUgyvYNVk9CIDsJ8Su2RIF2B"
    volumes:
      - migration_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "sl_5MQeo7tjZWvRn0rqtGHzvDAyk8EpR"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  migration_data:
  migration_test_data:
